# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('personterm', models.CharField(max_length=200)),
                ('personplural', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='marine',
            name='command',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fundraising.Command'),
        ),
    ]
