# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_auto_20160615_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marine',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundraising.Command'),
        ),
    ]
