# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0005_auto_20160616_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marine',
            name='command',
        ),
    ]
