# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0006_remove_marine_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='marine',
            name='command',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fundraising.Command'),
        ),
    ]
