# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0007_marine_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_pullup', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Amount Donated')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=50)),
                ('payer_id', models.CharField(max_length=50)),
                ('correlation_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('billing_agreement_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='marine',
            new_name='service_member',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='public',
        ),
        migrations.AddField(
            model_name='donation',
            name='correlation_id',
            field=models.CharField(default='testfix', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(default='anguslmm@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='Angus McLean', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='payer_id',
            field=models.CharField(default=666, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='INIT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='token',
            field=models.CharField(default='faketoken', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marine',
            name='pull_ups',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.AddField(
            model_name='pledge',
            name='service_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundraising.Marine'),
        ),
    ]
