# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0008_auto_20160707_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount_per_pullup',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Amount Pledged Per Pullup'),
        ),
    ]
