# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0009_auto_20160724_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marine',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Amount Raised'),
        ),
    ]
