# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0010_auto_20160821_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
